name: "run-doteki"
description: "Update README with dynamic content using dōteki"
author: "Óscar <osc@osc.garden>"

inputs:
  working-directory:
    description: "Working directory"
    required: false
    default: '.'  # Default to the repository root directory.

branding:
  icon: 'file-text'
  color: 'green'

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --quiet doteki[all]==v0.0.9  # Install all plugin dependencies.

    - name: Run dōteki
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        doteki

    - name: Commit and push changes
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        # If we're in dry-run mode, just show the diff and exit.
        if [[ "$DRY_RUN" == "true" ]]; then
          echo "DRY RUN: Would make the following changes:"
          git diff --staged
          exit
        fi

        # Otherwise proceed with commit and push.
        git config user.name "doteki-action"
        git config user.email "actions@users.noreply.github.com"
        git commit -m "Update README"
        git push
